[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"

remappings = [
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    'erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/',
    'forge-std/=lib/forge-std/src/',
    'ds-test/=lib/forge-std/lib/ds-test/src/'
]

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[fuzz]
seed = "0x1"

[invariant]
runs = 1000
depth = 32
fail_on_revert = true